// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingInfra;

namespace ShoppingInfra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingCartEntity.CategoryModel", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShoppingCartEntity.ProductsModel", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductPrize")
                        .HasColumnType("int");

                    b.Property<int>("ProductSize")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("02bb10c6-fa0f-4f3e-9171-27d457ba28fa"),
                            ProductColor = "0xFFFB7883",
                            ProductDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.",
                            ProductImage = "assets/images/bag_5.png",
                            ProductName = "Woman Fashion",
                            ProductPrize = 234,
                            ProductSize = 18
                        },
                        new
                        {
                            ProductId = new Guid("62f0b64b-cd51-4980-a5e0-0f2ddec1f84c"),
                            ProductColor = "0xFFAEAEAE",
                            ProductDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.",
                            ProductImage = "assets/images/bag_4.png",
                            ProductName = "New Fashion",
                            ProductPrize = 165,
                            ProductSize = 10
                        },
                        new
                        {
                            ProductId = new Guid("71155562-f71e-493d-bc4a-7fd294df7a9d"),
                            ProductColor = "0xFFE6B398",
                            ProductDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.",
                            ProductImage = "assets/images/bag_3.png",
                            ProductName = "Old Fashion",
                            ProductPrize = 186,
                            ProductSize = 14
                        },
                        new
                        {
                            ProductId = new Guid("36ba0a04-a18c-4d3e-b11c-33cd9101f490"),
                            ProductColor = "0xFF3D82AE",
                            ProductDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.",
                            ProductImage = "assets/images/bag_2.png",
                            ProductName = "Office Code",
                            ProductPrize = 135,
                            ProductSize = 12
                        },
                        new
                        {
                            ProductId = new Guid("afb6d141-849a-407a-8ff2-242eda21a3b7"),
                            ProductColor = "0xFFD3A984",
                            ProductDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.",
                            ProductImage = "assets/images/bag_1.png",
                            ProductName = "Belt Bag",
                            ProductPrize = 100,
                            ProductSize = 17
                        });
                });

            modelBuilder.Entity("ShoppingCartEntity.SubCategoryModel", b =>
                {
                    b.Property<Guid>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("ShoppingCartEntity.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c5e655b2-8c5c-4a89-8e80-832a3719a7ef"),
                            UserName = "Hemanth",
                            UserPassword = "12345",
                            UserRole = "user"
                        },
                        new
                        {
                            UserId = new Guid("03133ec8-b347-4a87-a4fc-775dc45c68c2"),
                            UserName = "Admin",
                            UserPassword = "12345",
                            UserRole = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
